# docker-compose.yml
services:
  datascience:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # Explicitly enable all GPUs for this service
    gpus: all
    environment:
      - ENV_NAME=marlins-ds-gpu
      - PYTHON_VER=3.10
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/workspace
    ports:
      - "8889:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
    command:
      [
        "conda", "run", "-n", "marlins-ds-gpu",
        "jupyter", "lab",
        "--ip", "0.0.0.0",
        "--port", "8888",
        "--no-browser",
        "--allow-root"
      ]
