# docker-compose.yml
services:
  datascience:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # Explicitly enable all GPUs for this service
    gpus: all
    environment:
      - ENV_NAME=marlins-ds-gpu
      - PYTHON_VER=3.10
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics,display
      
      # JAX GPU Configuration
      - JAX_PLATFORM_NAME=gpu
      - XLA_PYTHON_CLIENT_PREALLOCATE=true
      - XLA_PYTHON_CLIENT_ALLOCATOR=platform
      - XLA_PYTHON_CLIENT_MEM_FRACTION=0.95
      - XLA_FLAGS=--xla_force_host_platform_device_count=1
      - JAX_DISABLE_JIT=false
      - JAX_ENABLE_X64=false
      - TF_FORCE_GPU_ALLOW_GROWTH=false
      - JAX_PREALLOCATION_SIZE_LIMIT_BYTES=8589934592  # 8GB limit
    volumes:
      - .:/workspace
    ports:
      - "8889:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
      - "8050:8050"  # explainerdashboard
      - "8501:8501"  # streamlit
    command:
      [
        "bash", "-c",
        "conda run -n marlins-ds-gpu python -c \"import pyjags; print('PyJAGS version:', pyjags.__version__)\" && conda run -n marlins-ds-gpu jupyter lab --ServerApp.crash_info=True --ip 0.0.0.0 --port 8888 --no-browser --allow-root"
      ]
    healthcheck:
      test: ["CMD", "conda", "run", "-n", "marlins-ds-gpu", "python", "-c", "import pyjags; print('PyJAGS', pyjags.__version__)"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

      