# docker-compose.yml
services:
  datascience:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # Explicitly enable all GPUs for this service
    gpus: all
    environment:
      - ENV_NAME=marlins-ds-gpu
      - PYTHON_VER=3.10
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics,display
      
      # JAX GPU Configuration
      - JAX_PLATFORM_NAME=gpu
      - XLA_PYTHON_CLIENT_PREALLOCATE=true
      - XLA_PYTHON_CLIENT_ALLOCATOR=platform
      - XLA_PYTHON_CLIENT_MEM_FRACTION=0.95
      - XLA_FLAGS=--xla_force_host_platform_device_count=1 --xla_gpu_deterministic_reductions
      - JAX_DISABLE_JIT=false
      - JAX_ENABLE_X64=false
      - TF_FORCE_GPU_ALLOW_GROWTH=false
      - JAX_PREALLOCATION_SIZE_LIMIT_BYTES=8589934592  # 8GB limit
    volumes:
      - .:/workspace
    ports:
      - "8889:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
      - "8050:8050"  # explainerdashboard
    command:
      [
        "bash", "-c",
        "conda run -n marlins-ds-gpu python -m pip install 'notebook>=7.2' && conda run -n marlins-ds-gpu python /workspace/.devcontainer/gpu_verify.py && conda run -n marlins-ds-gpu jupyter lab --ServerApp.crash_info=True --ip 0.0.0.0 --port 8888 --no-browser --allow-root"
      ]

      