services:
  marlins-jax:
    build:
      context: .
      dockerfile: Dockerfile
    image: marlins-jax:latest
    container_name: marlins-jax
    volumes:
      - .:/app
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTENSOR_FLAGS=mode=JAX,floatX=float32
      - XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1
      - JAX_PLATFORMS=cpu,cuda
    # Run the GPU test script by default
    command: python3 gpu_testing/gpu_test.py
    stdin_open: true
    tty: true 