# .devcontainer/environment.yml
name: marlins-ds-gpu
channels:
  - conda-forge
  - defaults

dependencies:
  # Core language & kernels
  - python=3.10
  - jupyterlab>=3.0.0
  - ipykernel
  - ipywidgets>=8.0.0
  - optuna=4.3.0

  # Data & ML libraries (conda)
  - numpy>=1.20.0
  - pandas>=1.2.0
  - scipy>=1.7.0
  - scikit-learn>=1.4.2
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - xgboost>=1.5.0
  - lightgbm>=3.3.0
  - catboost>=1.0.0

  # Node for widgets & front-end tools
  - nodejs>=18.0.0

  # Bayesian & JAX-adjacent (conda)
  - numpyro>=0.18.0
  - pymc>=5.0.0
  - arviz>=0.14.0
  - statsmodels>=0.13.0

  # JAGS libraries as conda fallback
  - jags>=4.3.0
  - pybind11>=2.9.0  # Compatible with Python 3.10
  - cxx-compiler
  - c-compiler
  - make
  - pkg-config
  
  # Streamlit for interactive dashboards
  - streamlit>=1.20.0

  # Utilities & extras (conda)
  - nutpie>=0.14.3 
  - tabulate>=0.9.0
  - tqdm>=4.67.0
  - pyarrow>=12.0.0
  - sqlalchemy
  - mysql-connector-python

  # Development tooling
  - pytest>=7.0.0
  - black>=23.0.0
  - isort>=5.0.0
  - flake8>=5.0.0
  - mypy>=1.0.0


  # Bayesian & JAX-adjacent (conda)
  - cmdstanpy>=1.2           # Stan front-end :contentReference[oaicite:5]{index=5}
  - cmdstan>=2.36            # CmdStan C++ backend :contentReference[oaicite:6]{index=6}
  - tensorflow-probability   # Probabilistic methods on TF :contentReference[oaicite:8]{index=8}


  # Ensure pip is available
  - pip

  # Pure-pip installs (no JAX here! it's handled in Dockerfile)
  - pip:
    - pytensor>=2.18.3
    - shap>=0.40.0
    - shapiq>=0.1.0
    - explainerdashboard>=0.3.0
    - shapash[report]>=2.3.0
    - bayesian-optimization
    - pretty_errors
    - gdown
    - invoke>=2.2
    # - tensorflow>=2.16         # Required for TFP :contentReference[oaicite:9]{index=9}
    # - tf-keras>=2.18.0 
    - tf-nightly
    - tf-keras-nightly
